% Computes N2F transformation operators with DFT-based coefficient truncation
% for vector fields using Kottler's equations in spherical coordinates
%
% This function constructs TRUNCATED operator matrices by decomposing the full
% angular dependency via FFT and retaining only low-frequency Fourier coefficients.
% This dramatically reduces computational cost for pattern computations.
%
% ALGORITHM:
%   1. Compute full N2F operators as in vf_n2fOpFields (all theta angles)
%   2. Apply 1D FFT along theta direction for each phi angle
%   3. Extract central low-frequency coefficients (indicating smooth patterns)
%   4. Higher harmonics (large-|k| DFT terms) are discarded as low-contribution
%   5. Resulting compressed operators: (2*nbrCoeffs+1) x 6*nPts x nPhi
%
% COEFFICIENT INDEXING:
%   - Full FFT: [0 1 2 ... N/2-1 -N/2+1 ... -2 -1]
%   - Retained: [0 1 2 ... nbrCoeffs | -nbrCoeffs ... -2 -1]  (DC + nbrCoeffs positive + nbrCoeffs negative)
%   - This exploits Hermitian symmetry for real-valued fields
%
% [Opt, Opp, nbrCoeffs] =  vf_n2fOpFieldsFFT(k0, z0, surfPos, surfN, dS, thetaFF, phiFF, nbrCoeffs)
%
% IN: k0, z0 = free-space wavenumber [rad/m] and characteristic impedance [Ohm]
%     surfPos = surface sampling points coordinates [m] (3 x nPts)
%     surfN = outwardly directed surface normals (3 x nPts)
%     dS = surface patch areas [m²] (1 x nPts)
%     thetaFF = polar angles [rad] (nTheta x nPhi), nTheta must be power of 2 for FFT
%     phiFF = azimuthal angles [rad] (nTheta x nPhi)
%     nbrCoeffs = number of positive/negative freq. coefficients to retain (input value)
%
% OUT: Opt = N2F theta-polarized operator with DFT truncation (2*nbrCoeffs+1 x 6*nPts x nPhi)
%      Opp = N2F phi-polarized operator with DFT truncation (2*nbrCoeffs+1 x 6*nPts x nPhi)
%      nbrCoeffs = effective number of coefficients stored (returned for verification)
%
% NOTE: Input nbrCoeffs is halved internally (floor(nbrCoeffs/2)) for Nyquist consideration
%       Typical usage: nbrCoeffs input = 32 results in 65 output coefficients per operator
%
% Laurent Ntibarikure
function [Opt, Opp, nbrCoeffs] =  vf_n2fOpFieldsFFT(k0, z0, surfPos, ...
  surfN, dS, thetaFF, phiFF, nbrCoeffs)

fprintf('#> Computing the n2f fields operators ... ')
tic();

sizet=size(thetaFF,1);
nbrCoeffs = floor(nbrCoeffs/2);  % Reduce for Nyquist criterion
% DFT coefficient indexing: retain DC (index 1) + positive freqs (1:nbrCoeffs) + negative freqs from end
coeffsInd=[1:nbrCoeffs+1,sizet-nbrCoeffs+1:sizet];  % [DC, pos freqs | neg freqs]

Opt = zeros(2*nbrCoeffs+1,size(surfPos,2)*6,size(thetaFF,2));
Opp = Opt;
dim = [sizet, size(surfPos,2)*3];

for j=1:size(thetaFF,2)
    
  RffVx=sin(thetaFF(:,j)).*cos(phiFF(:,j));
  RffVy=sin(thetaFF(:,j)).*sin(phiFF(:,j));
  RffVz=cos(thetaFF(:,j));

  t_x=cos(thetaFF(:,j)).*cos(phiFF(:,j));
  t_y=cos(thetaFF(:,j)).*sin(phiFF(:,j));
  t_z=-sin(thetaFF(:,j));
  p_x=-sin(phiFF(:,j));
  p_y=cos(phiFF(:,j));

  green = -1i*k0/(4*pi).*exp(1i*k0*(RffVx*surfPos(1,:)+...
    RffVy*surfPos(2,:) +RffVz*surfPos(3,:)));

  OptE = [ green.*(-(t_x*surfN(3,:)) .* ((RffVz)*dS) + ...
    (t_x*surfN(2,:)) .* ((-RffVy)*dS) - ...
    (t_y*surfN(3,:)) .* zeros(size(thetaFF,1),size(surfPos,2)) + ...
    (t_y*surfN(2,:)) .* ((RffVx)*dS) - ...
    (t_z*surfN(3,:)) .* ((-RffVx)*dS) + ...
    (t_z*surfN(2,:)) .* zeros(size(thetaFF,1),size(surfPos,2))) ; ...
    green.*(-(t_x*surfN(1,:)) .* ((-RffVy)*dS) + ...
    (t_x*surfN(3,:)).* zeros(size(thetaFF,1),size(surfPos,2)) - ...
    (t_y*surfN(1,:)) .* ((RffVx)*dS) + ...
    (t_y*surfN(3,:)) .* ((-RffVz)*dS) -...
    (t_z*surfN(1,:)).*zeros(size(thetaFF,1),size(surfPos,2)) + ...
    (t_z*surfN(3,:)) .* ((RffVy)*dS)); ... 
    green.*(-(t_x*surfN(2,:)).*zeros(size(thetaFF,1),size(surfPos,2)) + ...
    (t_x*surfN(1,:)) .* ((RffVz)*dS) - ...
    (t_y*surfN(2,:)) .* ((-RffVz)*dS) + ...
    (t_y*surfN(1,:)).*zeros(size(thetaFF,1),size(surfPos,2)) - ...
    (t_z*surfN(2,:)) .* ((RffVy)*dS) + ...
    (t_z*surfN(1,:)) .* ((-RffVx)*dS)) ];

  OptH = [ green .*((t_x*surfN(3,:)).*z0 .* ((-RffVy.*RffVx)*dS) - ...
    (t_x*surfN(2,:)).*z0 .* ((-RffVz.*RffVx)*dS) + ...
    (t_y*surfN(3,:)).*z0 .* ((1-RffVy.*RffVy)*dS) - ...
    (t_y*surfN(2,:)).*z0 .* ((-RffVz.*RffVy)*dS) + ...
    (t_z*surfN(3,:)).*z0 .* ((-RffVy.*RffVz)*dS) - ...
    (t_z*surfN(2,:)).*z0 .* ((1-RffVz.*RffVz)*dS)); ...
     green .*((t_x*surfN(1,:)).*z0 .* ((-RffVz.*RffVx)*dS) - ...
    (t_x*surfN(3,:)).*z0 .* ((1-RffVx.*RffVx)*dS) + ...
    (t_y*surfN(1,:)).*z0 .* ((-RffVz.*RffVy)*dS) - ...
    (t_y*surfN(3,:)).*z0 .* ((-RffVx.*RffVy)*dS) + ...
    (t_z*surfN(1,:)).*z0 .* ((1-RffVz.*RffVz)*dS) - ...
    (t_z*surfN(3,:)).*z0 .* ((-RffVx.*RffVz)*dS)); ...
    green .*((t_x*surfN(2,:)).*z0 .* ((1-RffVx.*RffVx)*dS) - ...
    (t_x*surfN(1,:)).*z0 .* ((-RffVy.*RffVx)*dS) + ...
    (t_y*surfN(2,:)).*z0 .* ((-RffVx.*RffVy)*dS) - ...
    (t_y*surfN(1,:)).*z0 .* ((1-RffVy.*RffVy)*dS) + ...
    (t_z*surfN(2,:)).*z0 .* ((-RffVx.*RffVz)*dS) - ...
    (t_z*surfN(1,:)).*z0 .* ((-RffVy.*RffVz)*dS)) ];

  tmp = fft([ vector2matrix(dim, OptH(:)), ...
    vector2matrix(dim, OptE(:)) ]);
  Opt(:,:,j) = tmp(coeffsInd,:);
  clear OptH OptE tmp;

  OppE = [ green.*(-(p_x*surfN(3,:)) .* ((RffVz)*dS) + ...
    (p_x*surfN(2,:)) .* ((-RffVy)*dS) - ...
    (p_y*surfN(3,:)).*zeros(size(thetaFF,1),size(surfPos,2)) + ...
    (p_y*surfN(2,:)) .* ((RffVx)*dS)) ; ...
    green.*(-(p_x*surfN(1,:)) .* ((-RffVy)*dS) + ...
    (p_x*surfN(3,:)).*zeros(size(thetaFF,1),size(surfPos,2)) - ...
    (p_y*surfN(1,:)) .* ((RffVx)*dS) + ...
    (p_y*surfN(3,:)) .* ((-RffVz)*dS)); ...
    green.*(-(p_x*surfN(2,:)).*zeros(size(thetaFF,1),size(surfPos,2)) + ...
    (p_x*surfN(1,:)) .* ((RffVz)*dS) - ...
    (p_y*surfN(2,:)) .* ((-RffVz)*dS) + ...
    (p_y*surfN(1,:)).*zeros(size(thetaFF,1),size(surfPos,2))) ];

  OppH = [ green.*((p_x*surfN(3,:)).*z0 .* ((-RffVy.*RffVx)*dS) - ...
    (p_x*surfN(2,:)).*z0 .* ((-RffVz.*RffVx)*dS) + ...
    (p_y*surfN(3,:)).*z0 .* ((1-RffVy.*RffVy)*dS) - ...
    (p_y*surfN(2,:)).*z0 .* ((-RffVz.*RffVy)*dS)); ...
    green.*((p_x*surfN(1,:)).*z0 .* ((-RffVz.*RffVx)*dS) - ...
    (p_x*surfN(3,:)).*z0 .* ((1-RffVx.*RffVx)*dS) + ...
    (p_y*surfN(1,:)).*z0 .* ((-RffVz.*RffVy)*dS) - ...
    (p_y*surfN(3,:)).*z0 .* ((-RffVx.*RffVy)*dS)) ; ...
    green.*((p_x*surfN(2,:)).*z0 .* ((1-RffVx.*RffVx)*dS) - ...
    (p_x*surfN(1,:)).*z0 .* ((-RffVy.*RffVx)*dS) + ...
    (p_y*surfN(2,:)).*z0 .* ((-RffVx.*RffVy)*dS) - ...
    (p_y*surfN(1,:)).*z0 .* ((1-RffVy.*RffVy)*dS)) ];    

  tmp = fft([vector2matrix(dim, OppH(:)),...
      vector2matrix(dim, OppE(:))]);
  Opp(:,:,j) = tmp(coeffsInd,:);
  clear OppH OppE tmp;    
end

nbrCoeffs = 2*nbrCoeffs+1;
fprintf('%2.4g s\n', toc());